trigger:
  batch: true
  branches:
    include:
      - main

jobs:
  - job: storybook
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
      - script: npm ci
        workingDirectory: docs/
      - script: npm run build-storybook
        workingDirectory: docs/
      - task: AzureStaticWebApp@0
        inputs:
          app_location: docs/storybook-static
          azure_static_web_apps_api_token: $(deployment_token)
