export const USER_TYPE_ANONYMOUS = "ANONYMOUS";
export const USER_TYPE_PCAADMIN = "PCA_ADMIN";
export const USER_TYPE_PROJECTMANAGER = "PROJECT_MANAGER";
export const USER_TYPE_ORGANIZATIONMANAGER = "ORGANIZATION_MANAGER";
export const USER_TYPE_MERCHANT = "MERCHANT";

export const WITHOUT_SUBSCRIPTION = "withoutSubscription";

export const CARD_STATUS_ASSIGNED = "ASSIGNED";
export const CARD_STATUS_UNASSIGNED = "UNASSIGNED";
export const CARD_STATUS_DEACTIVATED = "DEACTIVATED";
export const CARD_STATUS_LOST = "LOST";

export const CHECK_CARD_STEPS_START = "START";
export const CHECK_CARD_STEPS_SCAN = "SCAN";
export const CHECK_CARD_STEPS_COMPLETE = "COMPLETE";

export const SORT_DEFAULT = "DEFAULT";
export const SORT_RANDOM = "RANDOM";

export const TRANSACTION_STEPS_START = "START";
export const TRANSACTION_STEPS_SCAN = "SCAN";
export const TRANSACTION_STEPS_ADD = "ADD";
export const TRANSACTION_STEPS_COMPLETE = "COMPLETE";

export const PRODUCT_GROUP_LOYALTY = "PCA::Loyalty";

export const BENEFICIARY_STATUS_INACTIVE = "INACTIVE";
export const BENEFICIARY_STATUS_ACTIVE = "ACTIVE";
