export const TOKEN_TYPE_CONFIRM_EMAIL = "CONFIRM_EMAIL";
export const TOKEN_TYPE_CREATE_USER = "CREATE_USER";
export const TOKEN_TYPE_RESET_PASSWORD = "RESET_PASSWORD";
export const TOKEN_TYPE_ADMIN_INVITATION = "ADMIN_INVITATION";
export const TOKEN_TYPE_PROJECT_MANAGER_INVITATION = "PROJECT_MANAGER_INVITATION";
export const TOKEN_TYPE_MERCHANT_INVITATION = "MERCHANT_INVITATION";
export const TOKEN_TYPE_ORGANIZATION_MANAGER_INVITATION = "ORGANIZATION_MANAGER_INVITATION";
export const TOKEN_TYPE_MARKET_GROUP_MANAGER_INVITATION = "MARKET_GROUP_MANAGER_INVITATION";

export const TOKEN_STATUS_INVALID = "INVALID";
export const TOKEN_STATUS_USER_CONFIRMED = "USER_CONFIRMED";
export const TOKEN_STATUS_VALID = "VALID";
